In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
path = '/Users/saisisir/Downloads/Sisir Entain Laptop/Self Learning /Machine Learning/Kaggle Practice/21. Xtreme Gradient Boosting'

In [3]:
df = pd.read_csv(path + '/diabetes.csv')

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
x = df.drop('Outcome', axis = 1)

In [6]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [7]:
y = df.loc[:, 'Outcome'].values

In [9]:
y = y.reshape(-1, 1)

In [10]:
#split x and y into training and test dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)    

In [11]:
#Create Gradient Boost classifier object
from xgboost import XGBClassifier
xgb = XGBClassifier()

xgb.fit(x_train, y_train)
y_pred = xgb.predict(x_test)

In [12]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[127  19]
 [ 34  51]]


In [13]:
#Accuracy Score or Recall
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)

print(ac)

0.7705627705627706


In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)   

In [21]:
xgb.fit(x_train, y_train)
y_pred = xgb.predict(x_test)

In [22]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[81 18]
 [20 35]]


In [23]:
ac = accuracy_score(y_test, y_pred)

print(ac)

0.7532467532467533


In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)    

In [25]:
xgb.fit(x_train, y_train)
y_pred = xgb.predict(x_test)

In [26]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[127  19]
 [ 34  51]]


In [27]:
ac = accuracy_score(y_test, y_pred)

print(ac)

0.7705627705627706


In [28]:
#Classification report
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)

print(cr)

              precision    recall  f1-score   support

           0       0.79      0.87      0.83       146
           1       0.73      0.60      0.66        85

    accuracy                           0.77       231
   macro avg       0.76      0.73      0.74       231
weighted avg       0.77      0.77      0.77       231



In [29]:
#check for bias and variance
bias = xgb.score(x_train, y_train) #Bias
variance = xgb.score(x_test, y_test)  #Variance

print(bias, variance)

1.0 0.7705627705627706
