In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
x = data.data
y = data.target

y = y.reshape(-1,1)

In [4]:
#split x and y into training and test dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [5]:
#Create ADABoost classifier object
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()

ada.fit(x_train, y_train)
y_pred = ada.predict(x_test)

C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [6]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[16  0  0]
 [ 0 17  1]
 [ 0  3  8]]


In [7]:
#Accuracy Score or Recall
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)

print(ac)

0.9111111111111111


In [8]:
#Classification report
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)

print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.85      0.94      0.89        18
           2       0.89      0.73      0.80        11

    accuracy                           0.91        45
   macro avg       0.91      0.89      0.90        45
weighted avg       0.91      0.91      0.91        45



In [9]:
#check for bias and variance
bias = ada.score(x_train, y_train)
variance = ada.score(x_test, y_test)

print(bias, variance)

0.9619047619047619 0.9111111111111111
