In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\sisir.sahu\Downloads\Machine Learning\Naive Bayes Classifier\titanic.csv')

In [3]:
pd.set_option('display.max_columns', None)
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
df1 = df.copy()

#Lets delete the features that dont matter on the survival of a passenger.
df.drop(['PassengerId', 'Name'], axis = 1, inplace = True)
df.drop(['SibSp', 'Parch', 'Ticket'], axis = 1, inplace = True)
df.drop(['Cabin', 'Embarked'], axis = 1, inplace = True)

In [5]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1].values

y = y.reshape(-1,1)

In [7]:
#convert categorical to numeric objects
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder() 

x['Sex'] = oe.fit_transform(x['Sex'].values.reshape(-1,1))

In [8]:
x.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [9]:
#Imputing with mean age across all null values
x['Age'] = x['Age'].fillna(x['Age'].mean())

In [10]:
x.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [11]:
#split x and y into training and test dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
#Scale the x train and test
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test =  scaler.transform(x_test)

In [13]:
#importing GaussianNB
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

y_pred = gnb.predict(x_test).reshape(-1,1)

C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [14]:
#Plotting confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[87 23]
 [16 53]]


In [15]:
#Finding accuracy
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.7821229050279329


In [16]:
#preparing classification report
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.79      0.82       110
           1       0.70      0.77      0.73        69

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.79      0.78      0.78       179



In [17]:
#Checking for bias and variance
gnb_bias = gnb.score(x_train, y_train)  
gnb_variance = gnb.score(x_test, y_test)

print(gnb_bias, gnb_variance)

0.7752808988764045 0.7821229050279329


In [18]:
#importing BernoulliNB
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(x_train, y_train)

y_pred_bnb = bnb.predict(x_test).reshape(-1,1)

C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [19]:
#Plotting confusion matrix
cm_bnb = confusion_matrix(y_test, y_pred_bnb)
print(cm_bnb)

[[90 20]
 [17 52]]


In [20]:
#Finding accuracy
ac_bnb = accuracy_score(y_test, y_pred_bnb)
print(ac_bnb)

0.7932960893854749


In [21]:
#preparing classification report
cr_bnb = classification_report(y_test, y_pred_bnb)
print(cr_bnb)

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       110
           1       0.72      0.75      0.74        69

    accuracy                           0.79       179
   macro avg       0.78      0.79      0.78       179
weighted avg       0.80      0.79      0.79       179



In [22]:
#Checking for bias and variance
bnb_bias = bnb.score(x_train, y_train)  
bnb_variance = bnb.score(x_test, y_test)

print(bnb_bias, bnb_variance)

0.7584269662921348 0.7932960893854749


In [23]:
#Implementing Cross Validation
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\sisir.sahu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ),

array([0.72727273, 0.8041958 , 0.77464789, 0.76760563, 0.81690141])

#The cross val score is not much significant than individual Gaussian and bernoulli models. We can ignore this. 